[workspace]
members = [
    "server",
    "common",
    "macros",
]
resolver = "2"

exclude = ["wasm"]

[profile.dev]
debug = 1

[profile.dev.build-override]
opt-level = 3

[profile.release]
lto = "fat"

[profile.dev.package.argon2]
opt-level = 3
