[package]
name = "isixhosa_server"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_qs = "0.8"
serde_with = "1.8"
fallible-iterator = "0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
warp = "0.3"
askama = { version = "0.10", features = ["with-warp"] }
askama_warp = "0.11.0"
rusqlite = "0.24"
pretty_env_logger = "0.4"
r2d2 = "0.8"
serde_json = "1"
r2d2_sqlite = "0.17"
num_enum = "0.5"
rust-argon2 = "0.8"
rand = "0.8"
base64 = "0.13"
unicode-normalization = "0.1"
reqwest = { version = "0.11", features = ["json"] }
itertools = "0.10"
arcstr = "1"
xtra = { version = "0.5", features = ["with-tokio-1"] }
percent-encoding = "2.1"
async-trait = "0.1"

smallvec = ">=1.6.1" # for rustsqlite - fixes vulnerability
