[package]
name = "isixhosa_pwa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.90" }
isixhosa_common = { path = "../../common" }
askama = { version = "0.12.1", features = ["serde-json"] }
serde-wasm-bindgen = "0.6.5"
